### ISSUE TITLE
Remove Unused models

### ISSUE THREAD

**Issue by harsh-not-haarsh** [devlup-labs/varchas#7]
Several unused models need to be removed from various apps:

- [ ]  Navbar Options

- [ ]  Home Image Carousel

**Comment by harsh-not-haarsh** [comment]
- [ ] Navbar Options
- [ ] Home Image Carousel

**Comment by likhita24** [comment]
I want to take up this issue

**Comment by harsh-not-haarsh** [comment]
@likhita24 you also need to figure out if there are any more models that are unused
